apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: postgres-secret 
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgresql.username }}
  password: {{ .Values.postgresql.password }}